name: Build Raphael 5.15 Docker Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build kernel
        uses: dabao1955/kernel_build_action@main
        with:
          # === 源码地址 ===
          kernel-url: https://github.com/HeliumStudio-Dev/kernel_xiaomi_raphael
          kernel-branch: main           # 或 5.15/lineage-21 等实际分支
          # === 基础参数 ===
          config: vendor/raphael_gki_defconfig
          arch: arm64
          android-version: 14           # 数字，无引号
          aosp-clang: true
          aosp-clang-version: r487747c  # 5.15 最低版本
          # === Docker 配置注入 ===
          extra-cmd: |
            sed -i '$a CONFIG_NAMESPACES=y CONFIG_NET_NS=y CONFIG_PID_NS=y CONFIG_IPC_NS=y CONFIG_UTS_NS=y CONFIG_CGROUPS=y CONFIG_CGROUP_CPUACCT=y CONFIG_CGROUP_DEVICE=y CONFIG_CGROUP_FREEZER=y CONFIG_CGROUP_SCHED=y CONFIG_CPUSETS=y CONFIG_MEMCG=y CONFIG_KEYS=y CONFIG_VETH=y CONFIG_BRIDGE=y CONFIG_BRIDGE_NETFILTER=y CONFIG_IP_NF_FILTER=y CONFIG_IP_NF_TARGET_MASQUERADE=y CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=y CONFIG_NETFILTER_XT_MATCH_CONNTRACK=y CONFIG_NETFILTER_XT_MATCH_IPVS=y CONFIG_NETFILTER_XT_MARK=y CONFIG_IP_NF_NAT=y CONFIG_NF_NAT=y CONFIG_POSIX_MQUEUE=y CONFIG_NF_NAT_IPV4=y CONFIG_NF_NAT_NEEDED=y CONFIG_CGROUP_BPF=y CONFIG_VT=y'
          # === 发布Release ===
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}
          anykernel3: true              # 自动打包成刷机zip
