name: Build Raphael 5.15 Docker Kernel

on:
  workflow_dispatch:   # 手动触发
  # push:              # 如想每次 push 都编，可去掉注释

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # 引用 jaye2720 的 action
      - name: Kernel Build
        uses: jaye2720/kernel_build_action@main
        with:
          # === 基础参数 ===
          arch: arm64
          compiler: clang
          clang_version: r487747c      # 5.15 最低版本
          config: vendor/raphael_gki_defconfig
          # === 打开 Docker 配置 ===
          extra_cmd: |
            sed -i '$a CONFIG_NAMESPACES=y CONFIG_NET_NS=y CONFIG_PID_NS=y CONFIG_IPC_NS=y CONFIG_UTS_NS=y CONFIG_CGROUPS=y CONFIG_CGROUP_CPUACCT=y CONFIG_CGROUP_DEVICE=y CONFIG_CGROUP_FREEZER=y CONFIG_CGROUP_SCHED=y CONFIG_CPUSETS=y CONFIG_MEMCG=y CONFIG_KEYS=y CONFIG_VETH=y CONFIG_BRIDGE=y CONFIG_BRIDGE_NETFILTER=y CONFIG_IP_NF_FILTER=y CONFIG_IP_NF_TARGET_MASQUERADE=y CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=y CONFIG_NETFILTER_XT_MATCH_CONNTRACK=y CONFIG_NETFILTER_XT_MATCH_IPVS=y CONFIG_NETFILTER_XT_MARK=y CONFIG_IP_NF_NAT=y CONFIG_NF_NAT=y CONFIG_POSIX_MQUEUE=y CONFIG_NF_NAT_IPV4=y CONFIG_NF_NAT_NEEDED=y CONFIG_CGROUP_BPF=y CONFIG_VT=y'
          # === 输出格式 ===
          zip_name: raphael-515-docker
          zip_rollback: true           # 同时生成 rollback.zip（boot 备份）
          upload_release: true         # 自动发 Release，方便直链下载
          release_tag: v5.15-docker    # 标签名可改
          release_title: Raphael 5.15 with Docker support
