name: Build 5.15 KSU+LXC+Docker Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Build kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/HeliumStudio-Dev/kernel_xiaomi_raphael
          kernel-branch: rikka-v2
          config: vendor/raphael_gki_defconfig
          arch: arm64
          android-version: 14
          # ===== 工具链 =====
          aosp-gcc: true
          aosp-clang: true
          aosp-clang-version: r487747c
          # 给模板一个可用的 GCC 仓库
          other-gcc64-url: https://github.com/kdrag0n/proton-gcc.git
          other-gcc64-branch: master
          other-gcc32-url: https://github.com/kdrag0n/proton-gcc-32.git
          other-gcc32-branch: master

          # ===== 三件套 =====
          ksu: true
          ksu-version: v0.9.5          # 非 GKI 锁死 0.9.5
          lxc: true
          lxc-patch: true
          # ===== 发布 =====
          anykernel3: true
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}
          # ===== Docker 扩展 =====
          extra-cmd: |
            sed -i '$a CONFIG_NAMESPACES=y CONFIG_NET_NS=y CONFIG_PID_NS=y CONFIG_IPC_NS=y CONFIG_UTS_NS=y CONFIG_CGROUPS=y CONFIG_CGROUP_CPUACCT=y CONFIG_CGROUP_DEVICE=y CONFIG_CGROUP_FREEZER=y CONFIG_CGROUP_SCHED=y CONFIG_CPUSETS=y CONFIG_MEMCG=y CONFIG_KEYS=y CONFIG_VETH=y CONFIG_BRIDGE=y CONFIG_BRIDGE_NETFILTER=y CONFIG_IP_NF_FILTER=y CONFIG_IP_NF_TARGET_MASQUERADE=y CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=y CONFIG_NETFILTER_XT_MATCH_CONNTRACK=y CONFIG_NETFILTER_XT_MATCH_IPVS=y CONFIG_NETFILTER_XT_MARK=y CONFIG_IP_NF_NAT=y CONFIG_NF_NAT=y CONFIG_POSIX_MQUEUE=y CONFIG_NF_NAT_IPV4=y CONFIG_NF_NAT_NEEDED=y CONFIG_CGROUP_BPF=y CONFIG_VT=y'
