name: Build 5.15 KSU+LXC+Docker Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Build kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/HeliumStudio-Dev/kernel_xiaomi_raphael
          kernel-branch: main
          config: vendor/raphael_gki_defconfig
          arch: arm64
          android-version: 14
          aosp-clang: true
          aosp-clang-version: r487747c
          lxc: true                    # 自动注入 LXC/Docker 配置 + 补丁
          lxc-patch: true              # 避免开容器后无法启动
          # ===== 额外 Docker 命名空间 =====
          extra-cmd: |
            sed -i '$a CONFIG_NAMESPACES=y CONFIG_NET_NS=y CONFIG_PID_NS=y CONFIG_IPC_NS=y CONFIG_UTS_NS=y CONFIG_CGROUPS=y CONFIG_CGROUP_CPUACCT=y CONFIG_CGROUP_DEVICE=y CONFIG_CGROUP_FREEZER=y CONFIG_CGROUP_SCHED=y CONFIG_CPUSETS=y CONFIG_MEMCG=y CONFIG_KEYS=y CONFIG_VETH=y CONFIG_BRIDGE=y CONFIG_BRIDGE_NETFILTER=y CONFIG_IP_NF_FILTER=y CONFIG_IP_NF_TARGET_MASQUERADE=y CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=y CONFIG_NETFILTER_XT_MATCH_CONNTRACK=y CONFIG_NETFILTER_XT_MATCH_IPVS=y CONFIG_NETFILTER_XT_MARK=y CONFIG_IP_NF_NAT=y CONFIG_NF_NAT=y CONFIG_POSIX_MQUEUE=y CONFIG_NF_NAT_IPV4=y CONFIG_NF_NAT_NEEDED=y CONFIG_CGROUP_BPF=y CONFIG_VT=y'
          # ===== 发布 =====
          anykernel3: true
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}
